name: Publish ds-portfolio-ui to ds-k8s staging
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Publish to Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build image
        run: docker build --platform=linux/amd64 -t ds-portfolio-ui .
      - name: Login to container registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: docker tag ds-portfolio-ui registry.digitalocean.com/ds-services-container/ds-portfolio-ui:${{ env.GITHUB_SHA }}
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/ds-services/container/ds-portfolio-ui:${{ env.GITHUB_SHA }}

  deploy:
    name: Configure and deploy to staging
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Helm Deploy
        run: helm hupgrade --install --create-namespace -n stg --set image.tag=${{ env.GITHUB_SHA }} ds-portfolio-ui ds-portfolio-ui